// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: infrastructure.proto

package mii

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateComponentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *CreateComponentsRequest) Reset() {
	*x = CreateComponentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infrastructure_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateComponentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateComponentsRequest) ProtoMessage() {}

func (x *CreateComponentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateComponentsRequest.ProtoReflect.Descriptor instead.
func (*CreateComponentsRequest) Descriptor() ([]byte, []int) {
	return file_infrastructure_proto_rawDescGZIP(), []int{0}
}

func (x *CreateComponentsRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type CreateComponentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *CreateComponentsResponse) Reset() {
	*x = CreateComponentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infrastructure_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateComponentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateComponentsResponse) ProtoMessage() {}

func (x *CreateComponentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateComponentsResponse.ProtoReflect.Descriptor instead.
func (*CreateComponentsResponse) Descriptor() ([]byte, []int) {
	return file_infrastructure_proto_rawDescGZIP(), []int{1}
}

func (x *CreateComponentsResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type DestroyComponentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *DestroyComponentsRequest) Reset() {
	*x = DestroyComponentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infrastructure_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyComponentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyComponentsRequest) ProtoMessage() {}

func (x *DestroyComponentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyComponentsRequest.ProtoReflect.Descriptor instead.
func (*DestroyComponentsRequest) Descriptor() ([]byte, []int) {
	return file_infrastructure_proto_rawDescGZIP(), []int{2}
}

func (x *DestroyComponentsRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type DestroyComponentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *DestroyComponentsResponse) Reset() {
	*x = DestroyComponentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infrastructure_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyComponentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyComponentsResponse) ProtoMessage() {}

func (x *DestroyComponentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyComponentsResponse.ProtoReflect.Descriptor instead.
func (*DestroyComponentsResponse) Descriptor() ([]byte, []int) {
	return file_infrastructure_proto_rawDescGZIP(), []int{3}
}

func (x *DestroyComponentsResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

var File_infrastructure_proto protoreflect.FileDescriptor

var file_infrastructure_proto_rawDesc = []byte{
	0x0a, 0x14, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a,
	0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x22, 0x32, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x22, 0x32, 0x0a, 0x18, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x33, 0x0a, 0x19, 0x44, 0x65, 0x73, 0x74,
	0x72, 0x6f, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x32, 0xc4, 0x01,
	0x0a, 0x15, 0x49, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x11,
	0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f,
	0x79, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72,
	0x6f, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x6d, 0x69, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_infrastructure_proto_rawDescOnce sync.Once
	file_infrastructure_proto_rawDescData = file_infrastructure_proto_rawDesc
)

func file_infrastructure_proto_rawDescGZIP() []byte {
	file_infrastructure_proto_rawDescOnce.Do(func() {
		file_infrastructure_proto_rawDescData = protoimpl.X.CompressGZIP(file_infrastructure_proto_rawDescData)
	})
	return file_infrastructure_proto_rawDescData
}

var file_infrastructure_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_infrastructure_proto_goTypes = []interface{}{
	(*CreateComponentsRequest)(nil),   // 0: proto.CreateComponentsRequest
	(*CreateComponentsResponse)(nil),  // 1: proto.CreateComponentsResponse
	(*DestroyComponentsRequest)(nil),  // 2: proto.DestroyComponentsRequest
	(*DestroyComponentsResponse)(nil), // 3: proto.DestroyComponentsResponse
}
var file_infrastructure_proto_depIdxs = []int32{
	0, // 0: proto.InfrastructureService.CreateComponents:input_type -> proto.CreateComponentsRequest
	2, // 1: proto.InfrastructureService.DestroyComponents:input_type -> proto.DestroyComponentsRequest
	1, // 2: proto.InfrastructureService.CreateComponents:output_type -> proto.CreateComponentsResponse
	3, // 3: proto.InfrastructureService.DestroyComponents:output_type -> proto.DestroyComponentsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_infrastructure_proto_init() }
func file_infrastructure_proto_init() {
	if File_infrastructure_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_infrastructure_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateComponentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infrastructure_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateComponentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infrastructure_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyComponentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infrastructure_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyComponentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_infrastructure_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_infrastructure_proto_goTypes,
		DependencyIndexes: file_infrastructure_proto_depIdxs,
		MessageInfos:      file_infrastructure_proto_msgTypes,
	}.Build()
	File_infrastructure_proto = out.File
	file_infrastructure_proto_rawDesc = nil
	file_infrastructure_proto_goTypes = nil
	file_infrastructure_proto_depIdxs = nil
}
